# Dependencies
markdown:         kramdown #redcarpet
highlighter:      rouge  #pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            All things
tagline:          'Deep Learning'
description:      'Natural Laguage Processing, Computer Vision, and more.'
url:              https://dzlab.github.io
baseurl:          /

author:
  name:           'bachirc'
  twitter:        https://twitter.com/bachiirc

paginate:         10

google_analytics: UA-128961990-1
analytics :
  mixpanel :
    token : '8d4b86545e94224d0e94429ea0bdd997'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dzlab

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-toc
  - jekyll-paginate

kramdown:
  parse_block_html: true
