# Dependencies
markdown:         kramdown #redcarpet
highlighter:      rouge  #pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            All things
tagline:          'Machie Learning'
description:      ''
url:              https://dzlab.github.io
baseurl:          / 

author:
  name:           'bachirc'
  twitter:        https://twitter.com/bachiirc

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dzlab

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
